#!/usr/bin/env bash
# Install nginx on my web01 server
# requirement:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# it must return a page that contains Holberton School
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
