#!/usr/bin/env bash
# Script to set HTTP response for two servers
sudo apt-get -y update
sudo apt-get -y install nginx
hostname=$(cat /etc/hostname)
sudo sed -i "37 i\ \tadd_header X-Served-By $hostname;\n" /etc/nginx/sites-enabled/default
service nginx restart
