#!/usr/bin/env bash
# Write a script that creat a file and others things.
pgrep -f 100-process_and_pid_file > /var/run/holbertonscript.pid
while true
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
do
    echo "To infinity and beyond"
    sleep 2
done
