#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd.
# script should only display: username, user id,home directory path for the user
while read line
do
    echo "$line" | cut -d':' -f1,3,6
done </etc/passwd
