#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration.
# displays good luck for the 8th loop iteration.
# displays Holberton School for the other iterations.
Hol=0
while [ $Hol -lt 10 ]; do
      if [ $Hol -eq 4 ]
      then
	echo bad luck
      elif [ $Hol -eq 8 ]
      then
	echo good luck
      else
	echo Holberton School
      fi
      let Hol+=1
done
