#!/usr/bin/env bash
# script displays a counter for hours and minutes.
# minutes from 1 to 59.
hour=0
minute=1
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    while [ $minute -lt 60 ]; do
	echo "$minute"
	let minute+=1
    done
    let hour+=1
done
